### ISSUE TITLE
Migrate rollback or reset gives 'Class not found' error

### ISSUE THREAD

**Issue by moleculezz** [creolab/laravel-modules#75]
I have  a problem with the default `php artisan migrate:rollback` or `php artisan migrate:reset`. Probably same issue with `refresh`

I get the following when executing it.

````
PHP Fatal error:  Class 'CreateExampleTable' not found in .../vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php on line 29
````

Seems like a namespace issue. I tried adding a namespace in the top of the migration class file. But no luck.
Anyone having this issue?

**Comment by koenhendriks** [comment]
+1 same issue

**Comment by shamshi1988** [comment]
Ya i also have the same problem but my problem now solved thnx to #mauvm  according to your answer my problem is solved thanx so much mauvm again for your help

**Comment by vqoph** [comment]
I had the same issue, solved with `composer update` thx to mauvm !

**Comment by munamuth** [comment]
I have the same problems. I have use $ php artisan dump-autoload, php artisan dump -o, composer update. but it still not work. Help me please

**Comment by whoisgregg** [comment]
Running `composer dump-autoload` will clear this issue _without_ updating your dependencies.
